### PR TITLE
sexy links in readme

### PR DESCRIPTION
**Pull request by Ozynt**

### CODE REVIEW

**Comment by harckepy** [comment]
busted, look how sexy they are

**Comment by harckepy** [comment]
HOW THE FUCK DO I FIX CONFLICTS

**Comment by Ozynt** [comment]
click ”marked as resolved" I think

**Comment by harckepy** [comment]
nice

**Comment by harckepy** [comment]
thanlks

**Comment by harckepy** [comment]
i messed up
why

**Pull request merged**
